import { Header } from './components/sections/Header';
import { HeroSection } from './components/sections/HeroSection';
import { TrustStrip } from './components/sections/TrustStrip';
import { PainPointSection } from './components/sections/PainPointSection';
import { ProductIntroSection } from './components/sections/ProductIntroSection';
import { GoldenFormulaSection } from './components/sections/GoldenFormulaSection';
import { FormulaMatrixSection } from './components/sections/FormulaMatrixSection';
import { SpfIgySection } from './components/sections/SpfIgySection';
import { IngredientFeatureSection } from './components/sections/IngredientFeatureSection';
import { OtherIngredientsSection } from './components/sections/OtherIngredientsSection';
import { AwardSection } from './components/sections/AwardSection';
import { BrandStrengthSection } from './components/sections/BrandStrengthSection';
import { QualityControlSection } from './components/sections/QualityControlSection';
import { ProductSpecSection } from './components/sections/ProductSpecSection';
import { UsageSection } from './components/sections/UsageSection';
import { AudienceSection } from './components/sections/AudienceSection';
import { ShippingPaymentSection } from './components/sections/ShippingPaymentSection';
import { FaqSection } from './components/sections/FaqSection';
import { CtaSection } from './components/sections/CtaSection';

export default function App() {return <main><Header/><HeroSection/><TrustStrip/><PainPointSection/><ProductIntroSection/><GoldenFormulaSection/><FormulaMatrixSection/><SpfIgySection/><IngredientFeatureSection/><OtherIngredientsSection/><AwardSection/><BrandStrengthSection/><QualityControlSection/><ProductSpecSection/><UsageSection/><AudienceSection/><ShippingPaymentSection/><FaqSection/><CtaSection/></main>;}
